// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: clawchain/participation/v1/epoch_info.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// EpochInfo defines the EpochInfo message.
type EpochInfo struct {
	CurrentEpoch   uint64 `protobuf:"varint,1,opt,name=current_epoch,json=currentEpoch,proto3" json:"current_epoch,omitempty"`
	EpochStartTime uint64 `protobuf:"varint,2,opt,name=epoch_start_time,json=epochStartTime,proto3" json:"epoch_start_time,omitempty"`
	EpochDuration  uint64 `protobuf:"varint,3,opt,name=epoch_duration,json=epochDuration,proto3" json:"epoch_duration,omitempty"`
	// total_reward_distributed in base denom (aclaw). String to support 18-decimal amounts.
	TotalRewardDistributed string `protobuf:"bytes,4,opt,name=total_reward_distributed,json=totalRewardDistributed,proto3" json:"total_reward_distributed,omitempty"`
}

func (m *EpochInfo) Reset()         { *m = EpochInfo{} }
func (m *EpochInfo) String() string { return proto.CompactTextString(m) }
func (*EpochInfo) ProtoMessage()    {}
func (*EpochInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_3535161c761b2583, []int{0}
}
func (m *EpochInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EpochInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EpochInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EpochInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EpochInfo.Merge(m, src)
}
func (m *EpochInfo) XXX_Size() int {
	return m.Size()
}
func (m *EpochInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_EpochInfo.DiscardUnknown(m)
}

var xxx_messageInfo_EpochInfo proto.InternalMessageInfo

func (m *EpochInfo) GetCurrentEpoch() uint64 {
	if m != nil {
		return m.CurrentEpoch
	}
	return 0
}

func (m *EpochInfo) GetEpochStartTime() uint64 {
	if m != nil {
		return m.EpochStartTime
	}
	return 0
}

func (m *EpochInfo) GetEpochDuration() uint64 {
	if m != nil {
		return m.EpochDuration
	}
	return 0
}

func (m *EpochInfo) GetTotalRewardDistributed() string {
	if m != nil {
		return m.TotalRewardDistributed
	}
	return ""
}

func init() {
	proto.RegisterType((*EpochInfo)(nil), "clawchain.participation.v1.EpochInfo")
}

func init() {
	proto.RegisterFile("clawchain/participation/v1/epoch_info.proto", fileDescriptor_3535161c761b2583)
}

var fileDescriptor_3535161c761b2583 = []byte{
	// 278 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0x31, 0x4b, 0xc3, 0x40,
	0x18, 0x86, 0x73, 0x5a, 0x84, 0x1e, 0x56, 0x24, 0x83, 0x04, 0x87, 0xa3, 0x28, 0x42, 0x40, 0x48,
	0x28, 0x2e, 0x0e, 0x4e, 0x52, 0x07, 0xd7, 0x28, 0x0e, 0x2e, 0xc7, 0xe5, 0x72, 0x35, 0x87, 0x49,
	0xee, 0xb8, 0x7c, 0x69, 0xf5, 0x5f, 0xf8, 0x7f, 0xfc, 0x03, 0x8e, 0x1d, 0x1d, 0x25, 0xf9, 0x23,
	0x92, 0x2f, 0xc5, 0x62, 0xd7, 0xe7, 0x7d, 0xee, 0x5e, 0xbe, 0x97, 0x5e, 0xca, 0x42, 0xac, 0x64,
	0x2e, 0x74, 0x15, 0x5b, 0xe1, 0x40, 0x4b, 0x6d, 0x05, 0x68, 0x53, 0xc5, 0xcb, 0x59, 0xac, 0xac,
	0x91, 0x39, 0xd7, 0xd5, 0xc2, 0x44, 0xd6, 0x19, 0x30, 0xfe, 0xe9, 0x9f, 0x1c, 0xfd, 0x93, 0xa3,
	0xe5, 0xec, 0xec, 0x93, 0xd0, 0xf1, 0x5d, 0xff, 0xe0, 0xbe, 0x5a, 0x18, 0xff, 0x9c, 0x4e, 0x64,
	0xe3, 0x9c, 0xaa, 0x80, 0xe3, 0x2f, 0x01, 0x99, 0x92, 0x70, 0x94, 0x1c, 0x6e, 0x20, 0x8a, 0x7e,
	0x48, 0x8f, 0x87, 0x8a, 0x1a, 0x84, 0x03, 0x0e, 0xba, 0x54, 0xc1, 0x1e, 0x7a, 0x47, 0xc8, 0x1f,
	0x7a, 0xfc, 0xa8, 0x4b, 0xe5, 0x5f, 0xd0, 0x81, 0xf0, 0xac, 0x71, 0xd8, 0x18, 0xec, 0xa3, 0x37,
	0x41, 0x3a, 0xdf, 0x40, 0xff, 0x9a, 0x06, 0x60, 0x40, 0x14, 0xdc, 0xa9, 0x95, 0x70, 0x19, 0xcf,
	0x74, 0x0d, 0x4e, 0xa7, 0x0d, 0xa8, 0x2c, 0x18, 0x4d, 0x49, 0x38, 0x4e, 0x4e, 0x30, 0x4f, 0x30,
	0x9e, 0x6f, 0xd3, 0xdb, 0xa7, 0xaf, 0x96, 0x91, 0x75, 0xcb, 0xc8, 0x4f, 0xcb, 0xc8, 0x47, 0xc7,
	0xbc, 0x75, 0xc7, 0xbc, 0xef, 0x8e, 0x79, 0xcf, 0x37, 0x2f, 0x1a, 0xf2, 0x26, 0x8d, 0xa4, 0x29,
	0xe3, 0xfe, 0xfc, 0xd4, 0x40, 0x5a, 0x18, 0xf9, 0x3a, 0x6c, 0xb6, 0x5d, 0xef, 0x6d, 0x67, 0x3f,
	0x78, 0xb7, 0xaa, 0x4e, 0x0f, 0x70, 0xb8, 0xab, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0f, 0x12,
	0x5c, 0xa3, 0x67, 0x01, 0x00, 0x00,
}

func (m *EpochInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EpochInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EpochInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TotalRewardDistributed) > 0 {
		i -= len(m.TotalRewardDistributed)
		copy(dAtA[i:], m.TotalRewardDistributed)
		i = encodeVarintEpochInfo(dAtA, i, uint64(len(m.TotalRewardDistributed)))
		i--
		dAtA[i] = 0x22
	}
	if m.EpochDuration != 0 {
		i = encodeVarintEpochInfo(dAtA, i, uint64(m.EpochDuration))
		i--
		dAtA[i] = 0x18
	}
	if m.EpochStartTime != 0 {
		i = encodeVarintEpochInfo(dAtA, i, uint64(m.EpochStartTime))
		i--
		dAtA[i] = 0x10
	}
	if m.CurrentEpoch != 0 {
		i = encodeVarintEpochInfo(dAtA, i, uint64(m.CurrentEpoch))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintEpochInfo(dAtA []byte, offset int, v uint64) int {
	offset -= sovEpochInfo(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *EpochInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CurrentEpoch != 0 {
		n += 1 + sovEpochInfo(uint64(m.CurrentEpoch))
	}
	if m.EpochStartTime != 0 {
		n += 1 + sovEpochInfo(uint64(m.EpochStartTime))
	}
	if m.EpochDuration != 0 {
		n += 1 + sovEpochInfo(uint64(m.EpochDuration))
	}
	l = len(m.TotalRewardDistributed)
	if l > 0 {
		n += 1 + l + sovEpochInfo(uint64(l))
	}
	return n
}

func sovEpochInfo(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEpochInfo(x uint64) (n int) {
	return sovEpochInfo(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *EpochInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEpochInfo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EpochInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EpochInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentEpoch", wireType)
			}
			m.CurrentEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEpochInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CurrentEpoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochStartTime", wireType)
			}
			m.EpochStartTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEpochInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EpochStartTime |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochDuration", wireType)
			}
			m.EpochDuration = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEpochInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EpochDuration |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalRewardDistributed", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEpochInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEpochInfo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEpochInfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TotalRewardDistributed = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEpochInfo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEpochInfo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEpochInfo(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEpochInfo
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEpochInfo
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEpochInfo
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEpochInfo
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEpochInfo
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEpochInfo
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEpochInfo        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEpochInfo          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEpochInfo = fmt.Errorf("proto: unexpected end of group")
)
