// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: clawchain/participation/v1/params.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the module.
type Params struct {
	EpochDuration uint64 `protobuf:"varint,1,opt,name=epoch_duration,json=epochDuration,proto3" json:"epoch_duration,omitempty"`
	// min_stake is the minimum staking amount in base denom (aclaw).
	// Stored as string to support 18-decimal token amounts that exceed uint64.
	MinStake       string `protobuf:"bytes,2,opt,name=min_stake,json=minStake,proto3" json:"min_stake,omitempty"`
	StakeWeight    uint64 `protobuf:"varint,3,opt,name=stake_weight,json=stakeWeight,proto3" json:"stake_weight,omitempty"`
	ActivityWeight uint64 `protobuf:"varint,4,opt,name=activity_weight,json=activityWeight,proto3" json:"activity_weight,omitempty"`
	UptimeWeight   uint64 `protobuf:"varint,5,opt,name=uptime_weight,json=uptimeWeight,proto3" json:"uptime_weight,omitempty"`
	// reward_pool_address is the module account that holds undistributed rewards.
	RewardPoolAddress string `protobuf:"bytes,6,opt,name=reward_pool_address,json=rewardPoolAddress,proto3" json:"reward_pool_address,omitempty"`
	// daily_reward_amount is the amount of aclaw distributed per epoch (in base denom).
	DailyRewardAmount string `protobuf:"bytes,7,opt,name=daily_reward_amount,json=dailyRewardAmount,proto3" json:"daily_reward_amount,omitempty"`
	// worker_reward_ratio is the percentage of daily rewards allocated to workers (0-100).
	// The remaining (100 - worker_reward_ratio) goes to validators.
	WorkerRewardRatio uint64 `protobuf:"varint,8,opt,name=worker_reward_ratio,json=workerRewardRatio,proto3" json:"worker_reward_ratio,omitempty"`
	// heartbeat_interval is the minimum seconds between worker heartbeats.
	HeartbeatInterval uint64 `protobuf:"varint,9,opt,name=heartbeat_interval,json=heartbeatInterval,proto3" json:"heartbeat_interval,omitempty"`
	// max_missed_heartbeats is the number of missed intervals before a worker is deactivated.
	MaxMissedHeartbeats uint64 `protobuf:"varint,10,opt,name=max_missed_heartbeats,json=maxMissedHeartbeats,proto3" json:"max_missed_heartbeats,omitempty"`
	// max_workers is the maximum number of worker registrations allowed (0 = unlimited).
	// Slots are permanent — unregistering does NOT free a slot.
	MaxWorkers uint64 `protobuf:"varint,11,opt,name=max_workers,json=maxWorkers,proto3" json:"max_workers,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_e80d6e67c5a47a50, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetEpochDuration() uint64 {
	if m != nil {
		return m.EpochDuration
	}
	return 0
}

func (m *Params) GetMinStake() string {
	if m != nil {
		return m.MinStake
	}
	return ""
}

func (m *Params) GetStakeWeight() uint64 {
	if m != nil {
		return m.StakeWeight
	}
	return 0
}

func (m *Params) GetActivityWeight() uint64 {
	if m != nil {
		return m.ActivityWeight
	}
	return 0
}

func (m *Params) GetUptimeWeight() uint64 {
	if m != nil {
		return m.UptimeWeight
	}
	return 0
}

func (m *Params) GetRewardPoolAddress() string {
	if m != nil {
		return m.RewardPoolAddress
	}
	return ""
}

func (m *Params) GetDailyRewardAmount() string {
	if m != nil {
		return m.DailyRewardAmount
	}
	return ""
}

func (m *Params) GetWorkerRewardRatio() uint64 {
	if m != nil {
		return m.WorkerRewardRatio
	}
	return 0
}

func (m *Params) GetHeartbeatInterval() uint64 {
	if m != nil {
		return m.HeartbeatInterval
	}
	return 0
}

func (m *Params) GetMaxMissedHeartbeats() uint64 {
	if m != nil {
		return m.MaxMissedHeartbeats
	}
	return 0
}

func (m *Params) GetMaxWorkers() uint64 {
	if m != nil {
		return m.MaxWorkers
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "clawchain.participation.v1.Params")
}

func init() {
	proto.RegisterFile("clawchain/participation/v1/params.proto", fileDescriptor_e80d6e67c5a47a50)
}

var fileDescriptor_e80d6e67c5a47a50 = []byte{
	// 453 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x4f, 0x6f, 0xd3, 0x30,
	0x18, 0xc6, 0x1b, 0x36, 0xca, 0xea, 0x6e, 0x43, 0xf5, 0x40, 0xb2, 0x8a, 0x94, 0x15, 0x10, 0xda,
	0x40, 0x22, 0xd1, 0xe0, 0x80, 0xc4, 0x6d, 0x88, 0x03, 0x1c, 0x90, 0x46, 0x39, 0x4c, 0xe2, 0x62,
	0xbd, 0x4d, 0xac, 0xc4, 0x5a, 0x1c, 0x47, 0xb6, 0xfb, 0xef, 0x2b, 0x70, 0xe2, 0x23, 0xf0, 0x11,
	0xf8, 0x18, 0x1c, 0x7b, 0xe4, 0x88, 0xda, 0x03, 0x7c, 0x08, 0x0e, 0x28, 0xaf, 0xd3, 0x20, 0x90,
	0x76, 0xa9, 0xdc, 0xe7, 0xf7, 0x7b, 0x9f, 0x58, 0xc9, 0x4b, 0x4e, 0x92, 0x02, 0xe6, 0x49, 0x0e,
	0xb2, 0x8c, 0x2b, 0x30, 0x4e, 0x26, 0xb2, 0x02, 0x27, 0x75, 0x19, 0xcf, 0xce, 0xea, 0x00, 0x94,
	0x8d, 0x2a, 0xa3, 0x9d, 0xa6, 0xc3, 0x56, 0x8c, 0xfe, 0x11, 0xa3, 0xd9, 0xd9, 0x70, 0x00, 0x4a,
	0x96, 0x3a, 0xc6, 0x5f, 0xaf, 0x0f, 0xef, 0x64, 0x3a, 0xd3, 0x78, 0x8c, 0xeb, 0x93, 0x4f, 0x1f,
	0xfc, 0xde, 0x21, 0xdd, 0x0b, 0x6c, 0xa5, 0x8f, 0xc8, 0xa1, 0xa8, 0x74, 0x92, 0xf3, 0x74, 0x6a,
	0xb0, 0x88, 0x05, 0xa3, 0xe0, 0x74, 0x77, 0x7c, 0x80, 0xe9, 0xeb, 0x26, 0xa4, 0xf7, 0x48, 0x4f,
	0xc9, 0x92, 0x5b, 0x07, 0x57, 0x82, 0xdd, 0x18, 0x05, 0xa7, 0xbd, 0xf1, 0x9e, 0x92, 0xe5, 0x87,
	0xfa, 0x3f, 0xbd, 0x4f, 0xf6, 0x11, 0xf0, 0xb9, 0x90, 0x59, 0xee, 0xd8, 0x0e, 0x36, 0xf4, 0x31,
	0xbb, 0xc4, 0x88, 0x9e, 0x90, 0xdb, 0x90, 0x38, 0x39, 0x93, 0x6e, 0xb9, 0xb5, 0x76, 0xd1, 0x3a,
	0xdc, 0xc6, 0x8d, 0xf8, 0x90, 0x1c, 0x4c, 0x2b, 0x27, 0x55, 0x5b, 0x76, 0x13, 0xb5, 0x7d, 0x1f,
	0x36, 0x52, 0x44, 0x8e, 0x8c, 0x98, 0x83, 0x49, 0x79, 0xa5, 0x75, 0xc1, 0x21, 0x4d, 0x8d, 0xb0,
	0x96, 0x75, 0xf1, 0x5e, 0x03, 0x8f, 0x2e, 0xb4, 0x2e, 0xce, 0x3d, 0xa8, 0xfd, 0x14, 0x64, 0xb1,
	0xe4, 0xcd, 0x14, 0x28, 0x3d, 0x2d, 0x1d, 0xbb, 0xe5, 0x7d, 0x44, 0x63, 0x24, 0xe7, 0x08, 0x6a,
	0x7f, 0xae, 0xcd, 0x95, 0x30, 0xdb, 0x01, 0x7c, 0x0b, 0x6c, 0x0f, 0xaf, 0x32, 0xf0, 0xc8, 0x0f,
	0x8c, 0x6b, 0x40, 0x9f, 0x12, 0x9a, 0x0b, 0x30, 0x6e, 0x22, 0xc0, 0x71, 0x59, 0x3a, 0x61, 0x66,
	0x50, 0xb0, 0x9e, 0xd7, 0x5b, 0xf2, 0xb6, 0x01, 0xf4, 0x19, 0xb9, 0xab, 0x60, 0xc1, 0x95, 0xb4,
	0x56, 0xa4, 0xbc, 0xe5, 0x96, 0x11, 0x9c, 0x38, 0x52, 0xb0, 0x78, 0x87, 0xec, 0x4d, 0x8b, 0xe8,
	0x31, 0xe9, 0xd7, 0x33, 0xfe, 0xd9, 0x96, 0xf5, 0xd1, 0x24, 0x0a, 0x16, 0x97, 0x3e, 0x79, 0xf9,
	0xf8, 0xd7, 0x97, 0xe3, 0xe0, 0xd3, 0xcf, 0xaf, 0x4f, 0x46, 0x7f, 0x57, 0x69, 0xf1, 0xdf, 0x32,
	0xf9, 0x6f, 0xfe, 0xea, 0xfd, 0xb7, 0x75, 0x18, 0xac, 0xd6, 0x61, 0xf0, 0x63, 0x1d, 0x06, 0x9f,
	0x37, 0x61, 0x67, 0xb5, 0x09, 0x3b, 0xdf, 0x37, 0x61, 0xe7, 0xe3, 0x8b, 0x4c, 0xba, 0x7c, 0x3a,
	0x89, 0x12, 0xad, 0xe2, 0x4a, 0x38, 0x23, 0x20, 0x13, 0xe5, 0x04, 0xb2, 0xf8, 0xfa, 0x4e, 0xb7,
	0xac, 0x84, 0x9d, 0x74, 0x71, 0xb1, 0x9e, 0xff, 0x09, 0x00, 0x00, 0xff, 0xff, 0xeb, 0x0c, 0x5b,
	0x7a, 0xc8, 0x02, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.EpochDuration != that1.EpochDuration {
		return false
	}
	if this.MinStake != that1.MinStake {
		return false
	}
	if this.StakeWeight != that1.StakeWeight {
		return false
	}
	if this.ActivityWeight != that1.ActivityWeight {
		return false
	}
	if this.UptimeWeight != that1.UptimeWeight {
		return false
	}
	if this.RewardPoolAddress != that1.RewardPoolAddress {
		return false
	}
	if this.DailyRewardAmount != that1.DailyRewardAmount {
		return false
	}
	if this.WorkerRewardRatio != that1.WorkerRewardRatio {
		return false
	}
	if this.HeartbeatInterval != that1.HeartbeatInterval {
		return false
	}
	if this.MaxMissedHeartbeats != that1.MaxMissedHeartbeats {
		return false
	}
	if this.MaxWorkers != that1.MaxWorkers {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MaxWorkers != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxWorkers))
		i--
		dAtA[i] = 0x58
	}
	if m.MaxMissedHeartbeats != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxMissedHeartbeats))
		i--
		dAtA[i] = 0x50
	}
	if m.HeartbeatInterval != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.HeartbeatInterval))
		i--
		dAtA[i] = 0x48
	}
	if m.WorkerRewardRatio != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.WorkerRewardRatio))
		i--
		dAtA[i] = 0x40
	}
	if len(m.DailyRewardAmount) > 0 {
		i -= len(m.DailyRewardAmount)
		copy(dAtA[i:], m.DailyRewardAmount)
		i = encodeVarintParams(dAtA, i, uint64(len(m.DailyRewardAmount)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.RewardPoolAddress) > 0 {
		i -= len(m.RewardPoolAddress)
		copy(dAtA[i:], m.RewardPoolAddress)
		i = encodeVarintParams(dAtA, i, uint64(len(m.RewardPoolAddress)))
		i--
		dAtA[i] = 0x32
	}
	if m.UptimeWeight != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.UptimeWeight))
		i--
		dAtA[i] = 0x28
	}
	if m.ActivityWeight != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.ActivityWeight))
		i--
		dAtA[i] = 0x20
	}
	if m.StakeWeight != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.StakeWeight))
		i--
		dAtA[i] = 0x18
	}
	if len(m.MinStake) > 0 {
		i -= len(m.MinStake)
		copy(dAtA[i:], m.MinStake)
		i = encodeVarintParams(dAtA, i, uint64(len(m.MinStake)))
		i--
		dAtA[i] = 0x12
	}
	if m.EpochDuration != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.EpochDuration))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.EpochDuration != 0 {
		n += 1 + sovParams(uint64(m.EpochDuration))
	}
	l = len(m.MinStake)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if m.StakeWeight != 0 {
		n += 1 + sovParams(uint64(m.StakeWeight))
	}
	if m.ActivityWeight != 0 {
		n += 1 + sovParams(uint64(m.ActivityWeight))
	}
	if m.UptimeWeight != 0 {
		n += 1 + sovParams(uint64(m.UptimeWeight))
	}
	l = len(m.RewardPoolAddress)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.DailyRewardAmount)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if m.WorkerRewardRatio != 0 {
		n += 1 + sovParams(uint64(m.WorkerRewardRatio))
	}
	if m.HeartbeatInterval != 0 {
		n += 1 + sovParams(uint64(m.HeartbeatInterval))
	}
	if m.MaxMissedHeartbeats != 0 {
		n += 1 + sovParams(uint64(m.MaxMissedHeartbeats))
	}
	if m.MaxWorkers != 0 {
		n += 1 + sovParams(uint64(m.MaxWorkers))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochDuration", wireType)
			}
			m.EpochDuration = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EpochDuration |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinStake", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MinStake = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StakeWeight", wireType)
			}
			m.StakeWeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StakeWeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActivityWeight", wireType)
			}
			m.ActivityWeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ActivityWeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UptimeWeight", wireType)
			}
			m.UptimeWeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UptimeWeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardPoolAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RewardPoolAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DailyRewardAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DailyRewardAmount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WorkerRewardRatio", wireType)
			}
			m.WorkerRewardRatio = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.WorkerRewardRatio |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HeartbeatInterval", wireType)
			}
			m.HeartbeatInterval = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.HeartbeatInterval |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxMissedHeartbeats", wireType)
			}
			m.MaxMissedHeartbeats = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxMissedHeartbeats |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxWorkers", wireType)
			}
			m.MaxWorkers = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxWorkers |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
