// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: clawchain/participation/v1/reward_record.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// RewardRecord defines the RewardRecord message.
type RewardRecord struct {
	Index string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	// reward_amount in base denom (aclaw). String to support 18-decimal amounts.
	RewardAmount  string `protobuf:"bytes,2,opt,name=reward_amount,json=rewardAmount,proto3" json:"reward_amount,omitempty"`
	StakeScore    uint64 `protobuf:"varint,3,opt,name=stake_score,json=stakeScore,proto3" json:"stake_score,omitempty"`
	ActivityScore uint64 `protobuf:"varint,4,opt,name=activity_score,json=activityScore,proto3" json:"activity_score,omitempty"`
	UptimeScore   uint64 `protobuf:"varint,5,opt,name=uptime_score,json=uptimeScore,proto3" json:"uptime_score,omitempty"`
	Claimed       bool   `protobuf:"varint,6,opt,name=claimed,proto3" json:"claimed,omitempty"`
	Epoch         uint64 `protobuf:"varint,7,opt,name=epoch,proto3" json:"epoch,omitempty"`
}

func (m *RewardRecord) Reset()         { *m = RewardRecord{} }
func (m *RewardRecord) String() string { return proto.CompactTextString(m) }
func (*RewardRecord) ProtoMessage()    {}
func (*RewardRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5e91f897b548e80, []int{0}
}
func (m *RewardRecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RewardRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RewardRecord.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RewardRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RewardRecord.Merge(m, src)
}
func (m *RewardRecord) XXX_Size() int {
	return m.Size()
}
func (m *RewardRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_RewardRecord.DiscardUnknown(m)
}

var xxx_messageInfo_RewardRecord proto.InternalMessageInfo

func (m *RewardRecord) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *RewardRecord) GetRewardAmount() string {
	if m != nil {
		return m.RewardAmount
	}
	return ""
}

func (m *RewardRecord) GetStakeScore() uint64 {
	if m != nil {
		return m.StakeScore
	}
	return 0
}

func (m *RewardRecord) GetActivityScore() uint64 {
	if m != nil {
		return m.ActivityScore
	}
	return 0
}

func (m *RewardRecord) GetUptimeScore() uint64 {
	if m != nil {
		return m.UptimeScore
	}
	return 0
}

func (m *RewardRecord) GetClaimed() bool {
	if m != nil {
		return m.Claimed
	}
	return false
}

func (m *RewardRecord) GetEpoch() uint64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func init() {
	proto.RegisterType((*RewardRecord)(nil), "clawchain.participation.v1.RewardRecord")
}

func init() {
	proto.RegisterFile("clawchain/participation/v1/reward_record.proto", fileDescriptor_c5e91f897b548e80)
}

var fileDescriptor_c5e91f897b548e80 = []byte{
	// 290 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xbd, 0x4e, 0xc3, 0x30,
	0x14, 0x85, 0x6b, 0xe8, 0x0f, 0xb8, 0x2d, 0x43, 0xc4, 0x60, 0x31, 0x98, 0x02, 0x42, 0xca, 0x94,
	0xa8, 0x62, 0x65, 0x81, 0x47, 0x08, 0x12, 0x03, 0x4b, 0xe5, 0x38, 0x16, 0xb1, 0x9a, 0xc4, 0x96,
	0x73, 0x93, 0xb6, 0x6f, 0xc1, 0x63, 0x31, 0x76, 0x64, 0x44, 0x09, 0x0f, 0x82, 0x62, 0x37, 0x20,
	0x18, 0xcf, 0xe7, 0xef, 0x5c, 0x59, 0x07, 0x07, 0x3c, 0x63, 0x1b, 0x9e, 0x32, 0x59, 0x84, 0x9a,
	0x19, 0x90, 0x5c, 0x6a, 0x06, 0x52, 0x15, 0x61, 0xbd, 0x0c, 0x8d, 0xd8, 0x30, 0x93, 0xac, 0x8c,
	0xe0, 0xca, 0x24, 0x81, 0x36, 0x0a, 0x94, 0x77, 0xf1, 0xe3, 0x07, 0x7f, 0xfc, 0xa0, 0x5e, 0x5e,
	0x7f, 0x21, 0x3c, 0x8b, 0x6c, 0x27, 0xb2, 0x15, 0xef, 0x1c, 0x8f, 0x64, 0x91, 0x88, 0x2d, 0x41,
	0x0b, 0xe4, 0x9f, 0x46, 0x2e, 0x78, 0x37, 0x78, 0x7e, 0xb8, 0xcc, 0x72, 0x55, 0x15, 0x40, 0x8e,
	0xec, 0xeb, 0xcc, 0xc1, 0x07, 0xcb, 0xbc, 0x4b, 0x3c, 0x2d, 0x81, 0xad, 0xc5, 0xaa, 0xe4, 0xca,
	0x08, 0x72, 0xbc, 0x40, 0xfe, 0x30, 0xc2, 0x16, 0x3d, 0x75, 0xc4, 0xbb, 0xc5, 0x67, 0x8c, 0x83,
	0xac, 0x25, 0xec, 0x0e, 0xce, 0xd0, 0x3a, 0xf3, 0x9e, 0x3a, 0xed, 0x0a, 0xcf, 0x2a, 0x0d, 0x32,
	0xef, 0x0f, 0x8d, 0xac, 0x34, 0x75, 0xcc, 0x29, 0x04, 0x4f, 0x78, 0xc6, 0x64, 0x2e, 0x12, 0x32,
	0x5e, 0x20, 0xff, 0x24, 0xea, 0x63, 0xf7, 0x7f, 0xa1, 0x15, 0x4f, 0xc9, 0xc4, 0xb6, 0x5c, 0x78,
	0x7c, 0x7e, 0x6f, 0x28, 0xda, 0x37, 0x14, 0x7d, 0x36, 0x14, 0xbd, 0xb5, 0x74, 0xb0, 0x6f, 0xe9,
	0xe0, 0xa3, 0xa5, 0x83, 0x97, 0xfb, 0x57, 0x09, 0x69, 0x15, 0x07, 0x5c, 0xe5, 0x61, 0xb7, 0x53,
	0xac, 0x20, 0xce, 0x14, 0x5f, 0xbb, 0x7d, 0x7f, 0x97, 0xde, 0xfe, 0xdb, 0x1a, 0x76, 0x5a, 0x94,
	0xf1, 0xd8, 0x2e, 0x7c, 0xf7, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x45, 0x65, 0xd6, 0x5b, 0x93, 0x01,
	0x00, 0x00,
}

func (m *RewardRecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RewardRecord) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RewardRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Epoch != 0 {
		i = encodeVarintRewardRecord(dAtA, i, uint64(m.Epoch))
		i--
		dAtA[i] = 0x38
	}
	if m.Claimed {
		i--
		if m.Claimed {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x30
	}
	if m.UptimeScore != 0 {
		i = encodeVarintRewardRecord(dAtA, i, uint64(m.UptimeScore))
		i--
		dAtA[i] = 0x28
	}
	if m.ActivityScore != 0 {
		i = encodeVarintRewardRecord(dAtA, i, uint64(m.ActivityScore))
		i--
		dAtA[i] = 0x20
	}
	if m.StakeScore != 0 {
		i = encodeVarintRewardRecord(dAtA, i, uint64(m.StakeScore))
		i--
		dAtA[i] = 0x18
	}
	if len(m.RewardAmount) > 0 {
		i -= len(m.RewardAmount)
		copy(dAtA[i:], m.RewardAmount)
		i = encodeVarintRewardRecord(dAtA, i, uint64(len(m.RewardAmount)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintRewardRecord(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintRewardRecord(dAtA []byte, offset int, v uint64) int {
	offset -= sovRewardRecord(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *RewardRecord) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovRewardRecord(uint64(l))
	}
	l = len(m.RewardAmount)
	if l > 0 {
		n += 1 + l + sovRewardRecord(uint64(l))
	}
	if m.StakeScore != 0 {
		n += 1 + sovRewardRecord(uint64(m.StakeScore))
	}
	if m.ActivityScore != 0 {
		n += 1 + sovRewardRecord(uint64(m.ActivityScore))
	}
	if m.UptimeScore != 0 {
		n += 1 + sovRewardRecord(uint64(m.UptimeScore))
	}
	if m.Claimed {
		n += 2
	}
	if m.Epoch != 0 {
		n += 1 + sovRewardRecord(uint64(m.Epoch))
	}
	return n
}

func sovRewardRecord(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozRewardRecord(x uint64) (n int) {
	return sovRewardRecord(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *RewardRecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRewardRecord
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RewardRecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RewardRecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRewardRecord
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRewardRecord
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRewardRecord
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRewardRecord
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRewardRecord
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRewardRecord
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RewardAmount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StakeScore", wireType)
			}
			m.StakeScore = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRewardRecord
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StakeScore |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActivityScore", wireType)
			}
			m.ActivityScore = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRewardRecord
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ActivityScore |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UptimeScore", wireType)
			}
			m.UptimeScore = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRewardRecord
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UptimeScore |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Claimed", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRewardRecord
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Claimed = bool(v != 0)
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Epoch", wireType)
			}
			m.Epoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRewardRecord
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Epoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipRewardRecord(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRewardRecord
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipRewardRecord(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowRewardRecord
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRewardRecord
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRewardRecord
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthRewardRecord
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupRewardRecord
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthRewardRecord
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthRewardRecord        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowRewardRecord          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupRewardRecord = fmt.Errorf("proto: unexpected end of group")
)
