// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: clawchain/participation/v1/validator_metrics.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ValidatorMetrics defines the ValidatorMetrics message.
type ValidatorMetrics struct {
	Index string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	// staked_amount in base denom (aclaw). String to support 18-decimal amounts.
	StakedAmount      string `protobuf:"bytes,2,opt,name=staked_amount,json=stakedAmount,proto3" json:"staked_amount,omitempty"`
	BlocksProposed    uint64 `protobuf:"varint,3,opt,name=blocks_proposed,json=blocksProposed,proto3" json:"blocks_proposed,omitempty"`
	TxProcessed       uint64 `protobuf:"varint,4,opt,name=tx_processed,json=txProcessed,proto3" json:"tx_processed,omitempty"`
	UptimeNumerator   uint64 `protobuf:"varint,5,opt,name=uptime_numerator,json=uptimeNumerator,proto3" json:"uptime_numerator,omitempty"`
	UptimeDenominator uint64 `protobuf:"varint,6,opt,name=uptime_denominator,json=uptimeDenominator,proto3" json:"uptime_denominator,omitempty"`
	LastActiveEpoch   uint64 `protobuf:"varint,7,opt,name=last_active_epoch,json=lastActiveEpoch,proto3" json:"last_active_epoch,omitempty"`
}

func (m *ValidatorMetrics) Reset()         { *m = ValidatorMetrics{} }
func (m *ValidatorMetrics) String() string { return proto.CompactTextString(m) }
func (*ValidatorMetrics) ProtoMessage()    {}
func (*ValidatorMetrics) Descriptor() ([]byte, []int) {
	return fileDescriptor_b10fa47a07c64bbb, []int{0}
}
func (m *ValidatorMetrics) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ValidatorMetrics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ValidatorMetrics.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ValidatorMetrics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidatorMetrics.Merge(m, src)
}
func (m *ValidatorMetrics) XXX_Size() int {
	return m.Size()
}
func (m *ValidatorMetrics) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidatorMetrics.DiscardUnknown(m)
}

var xxx_messageInfo_ValidatorMetrics proto.InternalMessageInfo

func (m *ValidatorMetrics) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *ValidatorMetrics) GetStakedAmount() string {
	if m != nil {
		return m.StakedAmount
	}
	return ""
}

func (m *ValidatorMetrics) GetBlocksProposed() uint64 {
	if m != nil {
		return m.BlocksProposed
	}
	return 0
}

func (m *ValidatorMetrics) GetTxProcessed() uint64 {
	if m != nil {
		return m.TxProcessed
	}
	return 0
}

func (m *ValidatorMetrics) GetUptimeNumerator() uint64 {
	if m != nil {
		return m.UptimeNumerator
	}
	return 0
}

func (m *ValidatorMetrics) GetUptimeDenominator() uint64 {
	if m != nil {
		return m.UptimeDenominator
	}
	return 0
}

func (m *ValidatorMetrics) GetLastActiveEpoch() uint64 {
	if m != nil {
		return m.LastActiveEpoch
	}
	return 0
}

func init() {
	proto.RegisterType((*ValidatorMetrics)(nil), "clawchain.participation.v1.ValidatorMetrics")
}

func init() {
	proto.RegisterFile("clawchain/participation/v1/validator_metrics.proto", fileDescriptor_b10fa47a07c64bbb)
}

var fileDescriptor_b10fa47a07c64bbb = []byte{
	// 330 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0xc1, 0x4e, 0xc2, 0x30,
	0x1c, 0xc6, 0x19, 0x02, 0xc6, 0x8a, 0x02, 0x8d, 0x87, 0xc5, 0xc3, 0x82, 0x7a, 0x10, 0x4d, 0xdc,
	0x82, 0x5e, 0xbd, 0x60, 0xf4, 0xa8, 0x21, 0x1c, 0x38, 0x78, 0x59, 0xba, 0xae, 0x91, 0x86, 0xad,
	0x6d, 0xd6, 0xff, 0xe6, 0x7c, 0x0b, 0xdf, 0xc0, 0xd7, 0xf1, 0xc8, 0xd1, 0xa3, 0x81, 0x17, 0x31,
	0x6b, 0x41, 0xa2, 0xc7, 0xfd, 0xbe, 0xdf, 0xb7, 0xb4, 0xfd, 0xd0, 0x35, 0x4d, 0xc8, 0x2b, 0x9d,
	0x11, 0x2e, 0x02, 0x45, 0x32, 0xe0, 0x94, 0x2b, 0x02, 0x5c, 0x8a, 0xa0, 0x18, 0x06, 0x05, 0x49,
	0x78, 0x4c, 0x40, 0x66, 0x61, 0xca, 0x20, 0xe3, 0x54, 0xfb, 0x2a, 0x93, 0x20, 0xf1, 0xf1, 0x6f,
	0xc7, 0xff, 0xd3, 0xf1, 0x8b, 0xe1, 0xe9, 0x47, 0x1d, 0x75, 0xa7, 0x9b, 0xde, 0xa3, 0xad, 0xe1,
	0x23, 0xd4, 0xe4, 0x22, 0x66, 0xa5, 0xeb, 0xf4, 0x9d, 0xc1, 0xde, 0xc4, 0x7e, 0xe0, 0x33, 0x74,
	0xa0, 0x81, 0xcc, 0x59, 0x1c, 0x92, 0x54, 0xe6, 0x02, 0xdc, 0xba, 0x49, 0xdb, 0x16, 0x8e, 0x0c,
	0xc3, 0xe7, 0xa8, 0x13, 0x25, 0x92, 0xce, 0x75, 0xa8, 0x32, 0xa9, 0xa4, 0x66, 0xb1, 0xbb, 0xd3,
	0x77, 0x06, 0x8d, 0xc9, 0xa1, 0xc5, 0xe3, 0x35, 0xc5, 0x27, 0xa8, 0x0d, 0x65, 0x25, 0x51, 0xa6,
	0x2b, 0xab, 0x61, 0xac, 0x7d, 0x28, 0xc7, 0x1b, 0x84, 0x2f, 0x50, 0x37, 0x57, 0xc0, 0x53, 0x16,
	0x8a, 0x3c, 0x65, 0x59, 0x75, 0x42, 0xb7, 0x69, 0xb4, 0x8e, 0xe5, 0x4f, 0x1b, 0x8c, 0xaf, 0x10,
	0x5e, 0xab, 0x31, 0x13, 0x32, 0xe5, 0xc2, 0xc8, 0x2d, 0x23, 0xf7, 0x6c, 0x72, 0xbf, 0x0d, 0xf0,
	0x25, 0xea, 0x25, 0x44, 0x43, 0x48, 0x28, 0xf0, 0x82, 0x85, 0x4c, 0x49, 0x3a, 0x73, 0x77, 0xed,
	0xaf, 0xab, 0x60, 0x64, 0xf8, 0x43, 0x85, 0xef, 0xa6, 0x9f, 0x4b, 0xcf, 0x59, 0x2c, 0x3d, 0xe7,
	0x7b, 0xe9, 0x39, 0xef, 0x2b, 0xaf, 0xb6, 0x58, 0x79, 0xb5, 0xaf, 0x95, 0x57, 0x7b, 0xbe, 0x7d,
	0xe1, 0x30, 0xcb, 0x23, 0x9f, 0xca, 0x34, 0xa8, 0x9e, 0x38, 0x92, 0x60, 0x2e, 0x69, 0xe7, 0xd9,
	0x0e, 0x55, 0xfe, 0x9b, 0x0a, 0xde, 0x14, 0xd3, 0x51, 0xcb, 0x8c, 0x73, 0xf3, 0x13, 0x00, 0x00,
	0xff, 0xff, 0xe6, 0xcd, 0x55, 0x65, 0xd2, 0x01, 0x00, 0x00,
}

func (m *ValidatorMetrics) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ValidatorMetrics) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ValidatorMetrics) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LastActiveEpoch != 0 {
		i = encodeVarintValidatorMetrics(dAtA, i, uint64(m.LastActiveEpoch))
		i--
		dAtA[i] = 0x38
	}
	if m.UptimeDenominator != 0 {
		i = encodeVarintValidatorMetrics(dAtA, i, uint64(m.UptimeDenominator))
		i--
		dAtA[i] = 0x30
	}
	if m.UptimeNumerator != 0 {
		i = encodeVarintValidatorMetrics(dAtA, i, uint64(m.UptimeNumerator))
		i--
		dAtA[i] = 0x28
	}
	if m.TxProcessed != 0 {
		i = encodeVarintValidatorMetrics(dAtA, i, uint64(m.TxProcessed))
		i--
		dAtA[i] = 0x20
	}
	if m.BlocksProposed != 0 {
		i = encodeVarintValidatorMetrics(dAtA, i, uint64(m.BlocksProposed))
		i--
		dAtA[i] = 0x18
	}
	if len(m.StakedAmount) > 0 {
		i -= len(m.StakedAmount)
		copy(dAtA[i:], m.StakedAmount)
		i = encodeVarintValidatorMetrics(dAtA, i, uint64(len(m.StakedAmount)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintValidatorMetrics(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintValidatorMetrics(dAtA []byte, offset int, v uint64) int {
	offset -= sovValidatorMetrics(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ValidatorMetrics) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovValidatorMetrics(uint64(l))
	}
	l = len(m.StakedAmount)
	if l > 0 {
		n += 1 + l + sovValidatorMetrics(uint64(l))
	}
	if m.BlocksProposed != 0 {
		n += 1 + sovValidatorMetrics(uint64(m.BlocksProposed))
	}
	if m.TxProcessed != 0 {
		n += 1 + sovValidatorMetrics(uint64(m.TxProcessed))
	}
	if m.UptimeNumerator != 0 {
		n += 1 + sovValidatorMetrics(uint64(m.UptimeNumerator))
	}
	if m.UptimeDenominator != 0 {
		n += 1 + sovValidatorMetrics(uint64(m.UptimeDenominator))
	}
	if m.LastActiveEpoch != 0 {
		n += 1 + sovValidatorMetrics(uint64(m.LastActiveEpoch))
	}
	return n
}

func sovValidatorMetrics(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozValidatorMetrics(x uint64) (n int) {
	return sovValidatorMetrics(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ValidatorMetrics) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowValidatorMetrics
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ValidatorMetrics: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ValidatorMetrics: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidatorMetrics
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthValidatorMetrics
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthValidatorMetrics
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StakedAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidatorMetrics
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthValidatorMetrics
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthValidatorMetrics
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StakedAmount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlocksProposed", wireType)
			}
			m.BlocksProposed = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidatorMetrics
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlocksProposed |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxProcessed", wireType)
			}
			m.TxProcessed = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidatorMetrics
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TxProcessed |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UptimeNumerator", wireType)
			}
			m.UptimeNumerator = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidatorMetrics
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UptimeNumerator |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UptimeDenominator", wireType)
			}
			m.UptimeDenominator = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidatorMetrics
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UptimeDenominator |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastActiveEpoch", wireType)
			}
			m.LastActiveEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowValidatorMetrics
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastActiveEpoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipValidatorMetrics(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthValidatorMetrics
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipValidatorMetrics(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowValidatorMetrics
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowValidatorMetrics
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowValidatorMetrics
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthValidatorMetrics
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupValidatorMetrics
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthValidatorMetrics
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthValidatorMetrics        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowValidatorMetrics          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupValidatorMetrics = fmt.Errorf("proto: unexpected end of group")
)
