// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: clawchain/participation/v1/worker.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// WorkerInfo defines a registered worker in the participation module.
type WorkerInfo struct {
	// index is the worker's address (bech32).
	Index string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	// name is the human-readable name of the worker.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// registered_at is the unix timestamp of registration.
	RegisteredAt uint64 `protobuf:"varint,3,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	// active indicates whether the worker is currently active.
	Active bool `protobuf:"varint,4,opt,name=active,proto3" json:"active,omitempty"`
	// heartbeat_count is the number of heartbeats in the current epoch.
	HeartbeatCount uint64 `protobuf:"varint,5,opt,name=heartbeat_count,json=heartbeatCount,proto3" json:"heartbeat_count,omitempty"`
	// last_heartbeat_time is the unix timestamp of the last heartbeat.
	LastHeartbeatTime uint64 `protobuf:"varint,6,opt,name=last_heartbeat_time,json=lastHeartbeatTime,proto3" json:"last_heartbeat_time,omitempty"`
	// last_active_epoch is the last epoch in which the worker was active.
	LastActiveEpoch uint64 `protobuf:"varint,7,opt,name=last_active_epoch,json=lastActiveEpoch,proto3" json:"last_active_epoch,omitempty"`
	// total_rewards_earned in base denom (aclaw). String for 18-decimal support.
	TotalRewardsEarned string `protobuf:"bytes,8,opt,name=total_rewards_earned,json=totalRewardsEarned,proto3" json:"total_rewards_earned,omitempty"`
}

func (m *WorkerInfo) Reset()         { *m = WorkerInfo{} }
func (m *WorkerInfo) String() string { return proto.CompactTextString(m) }
func (*WorkerInfo) ProtoMessage()    {}
func (*WorkerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0c255cb73b35108, []int{0}
}
func (m *WorkerInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *WorkerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_WorkerInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *WorkerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkerInfo.Merge(m, src)
}
func (m *WorkerInfo) XXX_Size() int {
	return m.Size()
}
func (m *WorkerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_WorkerInfo proto.InternalMessageInfo

func (m *WorkerInfo) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *WorkerInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *WorkerInfo) GetRegisteredAt() uint64 {
	if m != nil {
		return m.RegisteredAt
	}
	return 0
}

func (m *WorkerInfo) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *WorkerInfo) GetHeartbeatCount() uint64 {
	if m != nil {
		return m.HeartbeatCount
	}
	return 0
}

func (m *WorkerInfo) GetLastHeartbeatTime() uint64 {
	if m != nil {
		return m.LastHeartbeatTime
	}
	return 0
}

func (m *WorkerInfo) GetLastActiveEpoch() uint64 {
	if m != nil {
		return m.LastActiveEpoch
	}
	return 0
}

func (m *WorkerInfo) GetTotalRewardsEarned() string {
	if m != nil {
		return m.TotalRewardsEarned
	}
	return ""
}

func init() {
	proto.RegisterType((*WorkerInfo)(nil), "clawchain.participation.v1.WorkerInfo")
}

func init() {
	proto.RegisterFile("clawchain/participation/v1/worker.proto", fileDescriptor_e0c255cb73b35108)
}

var fileDescriptor_e0c255cb73b35108 = []byte{
	// 338 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0xcd, 0x4a, 0xeb, 0x40,
	0x14, 0x80, 0x9b, 0xde, 0xb6, 0xb7, 0x77, 0xb8, 0xf7, 0x16, 0xc7, 0x22, 0x83, 0x8b, 0x50, 0x74,
	0xd1, 0xe2, 0x22, 0xb1, 0xb8, 0x70, 0x5d, 0xa5, 0xa0, 0x4b, 0x83, 0x20, 0xb8, 0x09, 0x27, 0xc9,
	0x31, 0x19, 0x6c, 0x66, 0xc2, 0xe4, 0xf4, 0xc7, 0xb7, 0xf0, 0x39, 0x7c, 0x12, 0x97, 0x5d, 0xba,
	0x94, 0xf6, 0x45, 0x24, 0x53, 0x6d, 0xd1, 0xdd, 0x9c, 0xef, 0xfb, 0x86, 0x61, 0x38, 0xac, 0x1f,
	0x4f, 0x60, 0x1e, 0x67, 0x20, 0x95, 0x5f, 0x80, 0x21, 0x19, 0xcb, 0x02, 0x48, 0x6a, 0xe5, 0xcf,
	0x86, 0xfe, 0x5c, 0x9b, 0x47, 0x34, 0x5e, 0x61, 0x34, 0x69, 0x7e, 0xb8, 0x0d, 0xbd, 0x6f, 0xa1,
	0x37, 0x1b, 0x1e, 0xbd, 0xd4, 0x19, 0xbb, 0xb3, 0xf1, 0xb5, 0x7a, 0xd0, 0xbc, 0xcb, 0x9a, 0x52,
	0x25, 0xb8, 0x10, 0x4e, 0xcf, 0x19, 0xfc, 0x09, 0x36, 0x03, 0xe7, 0xac, 0xa1, 0x20, 0x47, 0x51,
	0xb7, 0xd0, 0x9e, 0xf9, 0x31, 0xfb, 0x67, 0x30, 0x95, 0x25, 0xa1, 0xc1, 0x24, 0x04, 0x12, 0xbf,
	0x7a, 0xce, 0xa0, 0x11, 0xfc, 0xdd, 0xc1, 0x11, 0xf1, 0x03, 0xd6, 0x82, 0x98, 0xe4, 0x0c, 0x45,
	0xa3, 0xe7, 0x0c, 0xda, 0xc1, 0xe7, 0xc4, 0xfb, 0xac, 0x93, 0x21, 0x18, 0x8a, 0x10, 0x28, 0x8c,
	0xf5, 0x54, 0x91, 0x68, 0xda, 0xeb, 0xff, 0xb7, 0xf8, 0xb2, 0xa2, 0xdc, 0x63, 0xfb, 0x13, 0x28,
	0x29, 0xdc, 0xd5, 0x24, 0x73, 0x14, 0x2d, 0x1b, 0xef, 0x55, 0xea, 0xea, 0xcb, 0xdc, 0xca, 0x1c,
	0xf9, 0x09, 0xb3, 0x30, 0xdc, 0xbc, 0x13, 0x62, 0xa1, 0xe3, 0x4c, 0xfc, 0xb6, 0x75, 0xa7, 0x12,
	0x23, 0xcb, 0xc7, 0x15, 0xe6, 0xa7, 0xac, 0x4b, 0x9a, 0x60, 0x12, 0x1a, 0x9c, 0x83, 0x49, 0xca,
	0x10, 0xc1, 0x28, 0x4c, 0x44, 0xdb, 0xfe, 0x92, 0x5b, 0x17, 0x6c, 0xd4, 0xd8, 0x9a, 0x8b, 0x9b,
	0xd7, 0x95, 0xeb, 0x2c, 0x57, 0xae, 0xf3, 0xbe, 0x72, 0x9d, 0xe7, 0xb5, 0x5b, 0x5b, 0xae, 0xdd,
	0xda, 0xdb, 0xda, 0xad, 0xdd, 0x9f, 0xa7, 0x92, 0xb2, 0x69, 0xe4, 0xc5, 0x3a, 0xf7, 0x0b, 0x24,
	0x83, 0x90, 0xa2, 0x8a, 0x20, 0xf5, 0x77, 0x3b, 0x5a, 0xfc, 0xd8, 0x12, 0x3d, 0x15, 0x58, 0x46,
	0x2d, 0xbb, 0xa2, 0xb3, 0x8f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xfb, 0x87, 0xe1, 0x9d, 0xcd, 0x01,
	0x00, 0x00,
}

func (m *WorkerInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *WorkerInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *WorkerInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TotalRewardsEarned) > 0 {
		i -= len(m.TotalRewardsEarned)
		copy(dAtA[i:], m.TotalRewardsEarned)
		i = encodeVarintWorker(dAtA, i, uint64(len(m.TotalRewardsEarned)))
		i--
		dAtA[i] = 0x42
	}
	if m.LastActiveEpoch != 0 {
		i = encodeVarintWorker(dAtA, i, uint64(m.LastActiveEpoch))
		i--
		dAtA[i] = 0x38
	}
	if m.LastHeartbeatTime != 0 {
		i = encodeVarintWorker(dAtA, i, uint64(m.LastHeartbeatTime))
		i--
		dAtA[i] = 0x30
	}
	if m.HeartbeatCount != 0 {
		i = encodeVarintWorker(dAtA, i, uint64(m.HeartbeatCount))
		i--
		dAtA[i] = 0x28
	}
	if m.Active {
		i--
		if m.Active {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if m.RegisteredAt != 0 {
		i = encodeVarintWorker(dAtA, i, uint64(m.RegisteredAt))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintWorker(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintWorker(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintWorker(dAtA []byte, offset int, v uint64) int {
	offset -= sovWorker(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *WorkerInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovWorker(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovWorker(uint64(l))
	}
	if m.RegisteredAt != 0 {
		n += 1 + sovWorker(uint64(m.RegisteredAt))
	}
	if m.Active {
		n += 2
	}
	if m.HeartbeatCount != 0 {
		n += 1 + sovWorker(uint64(m.HeartbeatCount))
	}
	if m.LastHeartbeatTime != 0 {
		n += 1 + sovWorker(uint64(m.LastHeartbeatTime))
	}
	if m.LastActiveEpoch != 0 {
		n += 1 + sovWorker(uint64(m.LastActiveEpoch))
	}
	l = len(m.TotalRewardsEarned)
	if l > 0 {
		n += 1 + l + sovWorker(uint64(l))
	}
	return n
}

func sovWorker(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozWorker(x uint64) (n int) {
	return sovWorker(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *WorkerInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWorker
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: WorkerInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: WorkerInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWorker
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWorker
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWorker
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWorker
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWorker
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWorker
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegisteredAt", wireType)
			}
			m.RegisteredAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWorker
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RegisteredAt |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Active", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWorker
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Active = bool(v != 0)
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HeartbeatCount", wireType)
			}
			m.HeartbeatCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWorker
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.HeartbeatCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastHeartbeatTime", wireType)
			}
			m.LastHeartbeatTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWorker
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastHeartbeatTime |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastActiveEpoch", wireType)
			}
			m.LastActiveEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWorker
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastActiveEpoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalRewardsEarned", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWorker
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWorker
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWorker
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TotalRewardsEarned = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipWorker(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthWorker
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipWorker(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowWorker
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowWorker
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowWorker
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthWorker
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupWorker
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthWorker
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthWorker        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowWorker          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupWorker = fmt.Errorf("proto: unexpected end of group")
)
